---
swagger: "2.0"
info:
  description: "Happily stealing everybody's packets, this service proxies \
    \ client requests to Acme Service and may inspect and edit the contents of the request.\
    \ A more detailed specification of the service's role and requirements as well\
    \ as the expected requests and responses are also available [here](https://docs.google.com/).\n\n"
  version: "1.0.0"
  title: "Acme-Proxy"
  termsOfService: ""
  contact:
    name: "Internal Team"
host: "acme.com"
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /health:
    get:
      summary: "Health endpoint"
      description: "Responds with 200 OK for health monitoring"
      parameters: []
      responses:
        200:
          description: "proxy is up and running"
  /api/v1:
    post:
      summary: "Inspect and Proxy requests and responses to Acme"
      description: "Proxy ads request to ACME_URL/api/v1 and attempt to open the\
        \ request and response to and from Acme for metrics"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
          description: "Acme request body"
        description: "Acme request body. Refer to [here](https://acme.com/sample-link) for more information on what is required in the body."
      responses:
        200:
          description: "Request was proxied and the response is from Acme"
          schema:
            type: "object"
            description: "Acme response body. It is okay if the decisions are null"
          examples:
            application/json:
                               user:
                                 key: 319deebac44e2c03c017eaf8e7cfa738055b6173
                               decisions:
                                 azk98276:
                                   id: 1791696
                                   clickUrl: 'http://acme.com/'
                                   contents:
                                     - type: raw
                                       body: '{}'
                                       data:
                                         height: 300
                                         width: 200
                                         customData:
                                           video:
                                             id: int_test
                                             url: 'http://acme.com/'
                                           custom:
                                             background_url_prefix: testv2
                                             title: The Girl on the Train
                                             hide_title: false
                                           type: dsv
                                       customTemplate: '{}'
                                   height: 300
                                   width: 200
                                   events:
                                     - id: 2
                                       url: 'http://acme.com'

        500:
          description: "The request could not be proxied through due to an internal\
            \ error in the proxy"
        502:
          description: "The request could not be proxied through due to an internal\
            \ error in the proxy"
        503:
          description: "The request could not be proxied through due to an internal\
            \ error in the proxy"
    options:
      summary: "Proxy directly to ACME_URL/api/v1"
      description: "Direct proxy to Acme"
      parameters: []
      responses:
        200:
          description: "Request was proxied and the response is from Acme"
        500:
          description: "The request could not be proxied through due to an internal\
            \ error in the proxy"
        502:
          description: "The request could not be proxied through due to an internal\
            \ error in the proxy"
        503:
          description: "The request could not be proxied through due to an internal\
            \ error in the proxy"
